### ISSUE TITLE
hummmm

### ISSUE THREAD

**Issue by fusco** [Khadija-Asa/projet-fallout#1]
```css
.noir {
	font-weight: bold;
	font-style: italic;
}

.noir1 {
	font-family: 'Roboto', sans-serif;
	font-style: italic;
}

.jaune {
	font-weight: bold;
	color: #F0AD2F;
	font-style: italic;
}

.jaune1 {
	color: #F0AD2F;
	font-style: italic;
}
```

Il est noir ... noir ? 
ou jaune ... jaune 

On entera que dans les class 'noir',   on ne donne même pas de couleur. 

on oublie aussi les noms de balises en FR
